package interfaz;

import javax.swing.JOptionPane;
import usaclibrary.USACLibrary;

/**
 *
 * @author cris
 */
public class crearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form crearUsuario
     */
    public crearUsuario() {
        initComponents();
        this.setLocationRelativeTo(null); // centra el frame en la pantalla
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtCarnet = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtCarrera = new javax.swing.JTextField();
        jtPass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 530));
        setMinimumSize(new java.awt.Dimension(430, 530));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("Crear Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 50, 130, 24);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Carnet:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 60, 16);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 60, 10);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 190, 48, 16);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Carrera:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 250, 47, 16);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 310, 61, 16);

        jtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCarnetActionPerformed(evt);
            }
        });
        getContentPane().add(jtCarnet);
        jtCarnet.setBounds(110, 80, 230, 28);
        getContentPane().add(jtNombre);
        jtNombre.setBounds(110, 130, 230, 28);
        getContentPane().add(jtApellido);
        jtApellido.setBounds(110, 180, 230, 28);
        getContentPane().add(jtCarrera);
        jtCarrera.setBounds(110, 240, 230, 28);
        getContentPane().add(jtPass);
        jtPass.setBounds(110, 300, 230, 28);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 370, 90, 28);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 370, 90, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCarnetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ventanaCargaMasiva().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtCarnet.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtCarrera.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            //capturar los posibles valores a almacenar en variables
            String Carnet = jtCarnet.getText();
            String nombre = jtNombre.getText();
            String apellido = jtApellido.getText();
            String carrera = jtCarrera.getText();
            String pass = jtPass.getText();
            //validar que el carnet no exista ya en el sistema
            if (!USACLibrary.hash.existeUsuario(Carnet)) { // si no existe el carnet registrado ingresar nuevo usuario
              
                USACLibrary.hash.funcionHash(Carnet, nombre, apellido, carrera, pass, USACLibrary.hash.getMd5(pass));
                JOptionPane.showMessageDialog(this, "Usuario Registrado Exitosamente", "AVISO", 1);
                USACLibrary.hash.graficaConsola();
            }
            else{
                JOptionPane.showMessageDialog(this, "Carnet Ya Registrado", "ERROR", 3);
            }
            
            //enviar al metodo de busqueda de tabla hash
           // Main.tablaUsuarios.modificar(Carnet, nombre, apellido, pass);
            //JOptionPane.showMessageDialog(this, "Usuario Modificado Exitosamente", "AVISO", 1);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCarnet;
    private javax.swing.JTextField jtCarrera;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPass;
    // End of variables declaration//GEN-END:variables
}
