/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;
import logica.NodoLista;
import usaclibrary.USACLibrary;

/**
 *
 * @author cris
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null); // centra el frame en la pantalla
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jtpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library");
        setMaximumSize(new java.awt.Dimension(520, 400));
        setMinimumSize(new java.awt.Dimension(520, 400));
        setPreferredSize(new java.awt.Dimension(520, 400));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("USAC Library");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 40, 170, 40);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 90, 80, 40);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 170, 130, 40);
        getContentPane().add(jtUsuario);
        jtUsuario.setBounds(110, 140, 310, 28);
        getContentPane().add(jtpass);
        jtpass.setBounds(110, 210, 310, 28);

        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 250, 130, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String txtusuario = jtUsuario.getText();
        String txtcontrasena = jtpass.getText();

        //almacena en la variable global para hacer validaciones
        usaclibrary.USACLibrary.UsuarioLogeado = txtusuario;
        usaclibrary.USACLibrary.ClaveUsuarioLogeado = txtcontrasena;

        if (jtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            //verificar si es el admin o un usuario
            //validar si se loguea el administrador
            if (txtusuario.equals("admin") && txtcontrasena.equals("admin")) {

                //creacion de la ventada del admin que maneja los usuarios
                JOptionPane.showMessageDialog(null, "Bienvenido Administrador");
                this.dispose(); // cerrar login
                //abrir la ventana de la libreria
                new Plataforma().setVisible(true);

            } //si no es el administrador buscar que el usuario exista en la hash
            //validar que el carnet  exista ya en el sistema
            else if (USACLibrary.hash.existeUsuario(txtusuario)) { // si  existe el carnet registrado ingresar plataforma

                //validar que el usuario existente este bien la contrasena
                NodoLista aux = USACLibrary.hash.busquedaModificar(USACLibrary.UsuarioLogeado); // obtener informacion de usuario logueado

                if (aux.carnet.equals(USACLibrary.UsuarioLogeado) && aux.password.equals(USACLibrary.ClaveUsuarioLogeado)) {
                    this.dispose(); // cerrar login
                    //abrir la ventana de la libreria
                    JOptionPane.showMessageDialog(null, "Bienvenido Carnet: "+USACLibrary.UsuarioLogeado);
                    new Plataforma().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "Alerta", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Credenciales no registradas en el sistema", "Alerta", JOptionPane.WARNING_MESSAGE);
                jtUsuario.setText("");
                jtpass.setText("");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JPasswordField jtpass;
    // End of variables declaration//GEN-END:variables
}
