package interfaz;

import javax.swing.JOptionPane;
import usaclibrary.USACLibrary;

/**
 *
 * @author cris
 */
public class modUsuario extends javax.swing.JFrame {

    /**
     * Creates new form modUsuario
     */
    public modUsuario(String carnet, String nombre, String apellido, String carrera, String password) {
        initComponents();
        this.jtmodCarnet.setText(carnet);
        this.jtmodCarnet.setEditable(false); // no deja editar el carnet
        this.jtmodNombre.setText(nombre);
        this.jtmodApellido.setText(apellido);
        this.jtmodCarrera.setText(carrera);
        this.jtmodPass.setText(password);

        this.setLocationRelativeTo(null); // centra el frame en la pantalla
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtmodCarnet = new javax.swing.JTextField();
        jtmodNombre = new javax.swing.JTextField();
        jtmodApellido = new javax.swing.JTextField();
        jtmodCarrera = new javax.swing.JTextField();
        jtmodPass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(430, 530));
        setMinimumSize(new java.awt.Dimension(430, 530));
        setPreferredSize(new java.awt.Dimension(430, 530));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("Modificar Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 220, 40);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Carnet:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 60, 19);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(28, 120, 60, 19);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 80, 19);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Carrera:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 60, 19);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 260, 80, 19);
        getContentPane().add(jtmodCarnet);
        jtmodCarnet.setBounds(100, 70, 260, 28);
        getContentPane().add(jtmodNombre);
        jtmodNombre.setBounds(100, 110, 260, 28);
        getContentPane().add(jtmodApellido);
        jtmodApellido.setBounds(100, 160, 260, 28);
        getContentPane().add(jtmodCarrera);
        jtmodCarrera.setBounds(100, 200, 260, 28);
        getContentPane().add(jtmodPass);
        jtmodPass.setBounds(100, 250, 260, 28);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 310, 110, 28);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 310, 110, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 440, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new biblioteca().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jtmodNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtmodApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtmodCarrera.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (jtmodPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "llenar Campo para continuar", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            //capturar los posibles valores a almacenar en variables
            String Carnet = jtmodCarnet.getText();
            String nombre = jtmodNombre.getText();
            String apellido = jtmodApellido.getText();
            String carrera = jtmodCarrera.getText();
            String pass = jtmodPass.getText();
       
            //modificar los datos

            USACLibrary.hash.modificar(Carnet, nombre, apellido, carrera, pass, pass);
            JOptionPane.showMessageDialog(this, "Usuario Modificado Exitosamente", "AVISO", 1);
                        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtmodApellido;
    private javax.swing.JTextField jtmodCarnet;
    private javax.swing.JTextField jtmodCarrera;
    private javax.swing.JTextField jtmodNombre;
    private javax.swing.JTextField jtmodPass;
    // End of variables declaration//GEN-END:variables
}
