/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import logica.NodoLista;

/**
 *
 * @author cris
 */
public class tablaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form tablaUsuario
     */
    public tablaUsuario() {
        initComponents();
        this.setLocationRelativeTo(null); // centra el frame en la pantalla
        this.setResizable(false);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 445));
        setMinimumSize(new java.awt.Dimension(950, 445));
        setPreferredSize(new java.awt.Dimension(950, 445));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 70, 840, 280);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuarios del Sistema");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 30, 250, 24);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 380, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/base.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(950, 445));
        jLabel1.setMinimumSize(new java.awt.Dimension(950, 445));
        jLabel1.setPreferredSize(new java.awt.Dimension(950, 445));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new biblioteca().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void mostrar() {

        //llenado del arreglo con la informacion a mostrar
        usaclibrary.USACLibrary.usuariosSistema.resetearLista(); // limpia la lista de usuarios del sistema

        // llenar la lista-----------------------------------------------------------------------------------------------
        //asignacion de id horizontal a las listas simples
        NodoLista arreg3 = usaclibrary.USACLibrary.hash.arreglo.primero; // referencia al arreglo de 45 espacios
        int espacio3 = 0; //nos dice en que espacio nos encontramos
        while (arreg3 != null) {

            NodoLista aux = arreg3.usuarios.primero;
            int col = 1;
            while (aux != null) {
                //enviar  a guardar en esa lista de usuarios del sistema
                usaclibrary.USACLibrary.usuariosSistema.insertarFinalUsuarioSistema(aux.carnet, aux.nombre, aux.apellido, aux.carrera, aux.password, aux.passMD5);
                aux = aux.siguiente;
                col++;
            }

            arreg3 = arreg3.siguiente;
            espacio3++;
        }

        String matriz[][] = new String[usaclibrary.USACLibrary.usuariosSistema.tamano][7]; // matriz para la tabla
        NodoLista aux = usaclibrary.USACLibrary.usuariosSistema.primero; // crecion de auxiliar para acceder a los atrubutos de cada usuario

        int i = 0; // variable que servira para crear filas
        int contar = 1;
        while (aux != null) {

            matriz[i][0] = Integer.toString(contar);
            matriz[i][1] = aux.carnet; // nombre del usuario
            matriz[i][2] = aux.nombre; // nombre del usuario
            matriz[i][3] = aux.apellido; // nombre del usuario
            matriz[i][4] = aux.carrera; // nombre del usuario
            matriz[i][5] = aux.password; // nombre del usuario
            matriz[i][6] = aux.passMD5; // nombre del usuario

            i++; //iterador de filas
            contar++;
            aux = aux.siguiente;
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "No.", "carnet", "nombre", "apellido", "carrera", "Password", "PassMD5"
                }
        ));
    }
}
