/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

//import logica.NodoLista;
import javax.swing.JOptionPane;
import logica.NodoLista;

/**
 *
 * @author cris
 */
public class tablaCategorias extends javax.swing.JFrame {

    /**
     * Creates new form tablaCategorias
     */
    public tablaCategorias() {
        initComponents();
        this.setLocationRelativeTo(null); // centra el frame en la pantalla
        this.setResizable(false);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 400));
        setMinimumSize(new java.awt.Dimension(720, 400));
        setPreferredSize(new java.awt.Dimension(720, 400));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setText("Categorias ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 10, 150, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 456, 280);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 110, 100, 28);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 180, 100, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int filaSelect = jTable1.getSelectedRow();

        if (filaSelect == -1) {

            JOptionPane.showMessageDialog(this, "Seleccione Cetegoria Primero", "AVISO", 1);

        } else {
            System.out.println("filaSelect " + filaSelect);

            //llamar al metodo para que borre de las categorias si es que es el propietario de la categoria
            String categoria = (String) jTable1.getValueAt(filaSelect, 0);
            System.out.println("categoria: " + categoria);
            String propietario = (String) jTable1.getValueAt(filaSelect, 1);
            System.out.println("propietario: " + propietario);
            
            //si es el propietario el logueado mandar a eliminar de AVL
            if (usaclibrary.USACLibrary.UsuarioLogeado.equals(propietario)) {
                
                
                usaclibrary.USACLibrary.arbolAvl.root =usaclibrary.USACLibrary.arbolAvl.deleteNode(usaclibrary.USACLibrary.arbolAvl.root, categoria);
                JOptionPane.showMessageDialog(this, "Categoria Eliminada Exitosamente", "AVISO", 1);

            } else {
                JOptionPane.showMessageDialog(this, "No puede Eliminar una categoria de otro usuario", "AVISO", 1);
            }

            mostrar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new biblioteca().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public void mostrar() {

        //llenado del arreglo con la informacion a mostrar
        usaclibrary.USACLibrary.recorridosAVL.resetearLista(); // limpiar lista
        usaclibrary.USACLibrary.arbolAvl.postOrdenReporte(usaclibrary.USACLibrary.arbolAvl.root); // llenar lista para reporte

        String matriz[][] = new String[usaclibrary.USACLibrary.recorridosAVL.tamano][2]; // matriz para la tabla
        NodoLista aux = usaclibrary.USACLibrary.recorridosAVL.primero; // crecion de auxiliar para acceder a los atrubutos de cada usuario

        int i = 0; // variable que servira para crear filas
        while (aux != null) {

            matriz[i][0] = aux.carnet;// categoria guardada en ese string llamado carnet
            matriz[i][1] = aux.nombre; // nombre del usuario

            i++; //iterador de filas

            aux = aux.siguiente;
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Categoria", "Creador"
                }
        ));
    }

}
